// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {z
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHjNOOH4A42nj3ZltGGPMKytFGDt6Ez3M',
    appId: '1:794586430495:web:aa56ce082f3ea709a1692a',
    messagingSenderId: '794586430495',
    projectId: 'lsv24-63def',
    authDomain: 'lsv24-63def.firebaseapp.com',
    storageBucket: 'lsv24-63def.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0uKn2J3rneCs3dnqTYwEwhD-9ATzA8sQ',
    appId: '1:794586430495:android:d5fad0c53ee61845a1692a',
    messagingSenderId: '794586430495',
    projectId: 'lsv24-63def',
    storageBucket: 'lsv24-63def.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuhTbODcG6sgf31u8qAkUAzAgp2dZcfhw',
    appId: '1:794586430495:ios:66320afab68f5edba1692a',
    messagingSenderId: '794586430495',
    projectId: 'lsv24-63def',
    storageBucket: 'lsv24-63def.firebasestorage.app',
    iosClientId: '794586430495-sod5vv1hgnbratqi73evi8skljh2k2nu.apps.googleusercontent.com',
    iosBundleId: 'com.live.metube',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDuhTbODcG6sgf31u8qAkUAzAgp2dZcfhw',
    appId: '1:794586430495:ios:503d1d2541c0ff55a1692a',
    messagingSenderId: '794586430495',
    projectId: 'lsv24-63def',
    storageBucket: 'lsv24-63def.firebasestorage.app',
    iosClientId: '794586430495-0r21f6j9b85jc17luu2jopj1p9732hl8.apps.googleusercontent.com',
    iosBundleId: 'com.meTube.live',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBHjNOOH4A42nj3ZltGGPMKytFGDt6Ez3M',
    appId: '1:794586430495:web:5a878708ba2412e8a1692a',
    messagingSenderId: '794586430495',
    projectId: 'lsv24-63def',
    authDomain: 'lsv24-63def.firebaseapp.com',
    storageBucket: 'lsv24-63def.firebasestorage.app',
  );
}
